const Symbol = require("./../src/translate/symbol/Symbol")
const SymbolTypes = require("./../src/translate/symbol/SymbolTypes")
const SymbolTable = require("./../src/translate/symbol/SymbolTable")
const TokenType = require("./../src/lexer/TokenType")
const Token = require("./../src/lexer/Token")

const st = new SymbolTable()
st.createLabel("l0", new Token(TokenType.VARIABLE, "foo"))
st.createVariable()
st.createSymbolByLexeme(new Token(TokenType.VARIABLE, "a"))
const st2 = new SymbolTable()
st2.createLabel("l0", new Token(TokenType.VARIABLE, "foo2"))
st.addChild(st2)
console.log(st.children[0])
